---
# variables:

when:
  - event: push
    branch: "add_s3cmd"
  - event: manual

matrix:
  include:
    - platform: linux/amd64
      clone_image: woodpeckerci/plugin-git
      build_image: docker
      socket_mount: /var/run/docker.sock:/var/run/docker.sock
    - platform: windows/amd64
      clone_image: opencloudeu/woodpecker-windows-git-plugin:v2
      build_image: winamd64/docker:windowsservercore-ltsc2022
      socket_mount: \\.\pipe\docker_engine:\\.\pipe\docker_engine

labels:
  platform: ${platform}
  backend: docker

clone:
  - name: clone
    image: ${clone_image}

steps:
  - name: build
    image: ${build_image}
    volumes:
      - ${socket_mount}
    commands:
      - docker build s3cmd -f s3cmd/Dockerfile -t opencloudeu/s3cmd
      - docker push opencloudeu/s3cmd
